app/models/__init__.py
from .user import * # noqa
from .author import * # noqa

app/models/author.py
from flask_sqlalchemy.model import sa
from app import db


class About(db.Model):
    __tablename__ = "about"

    id = sa.Column(sa.Integer, primary_key=True)
    first_name = sa.Column(sa.String(100), nullable=False)
    last_name = sa.Column(sa.String(100), nullable=False)
    birthday = sa.Column(sa.DateTime, nullable=False)
    website = sa.Column(sa.String(200), nullable=True)
    phone = sa.Column(sa.String(14), nullable=False)
    city = sa.Column(sa.String(100), nullable=False)
    age = sa.Column(sa.Integer, nullable=False, default=0)
    degree = sa.Column(sa.String(7), nullable=True)
    email = sa.Column(sa.String(60), nullable=False)
    freelance = sa.Column(sa.String(60), nullable=True)
    is_active = sa.Column(sa.Boolean, nullable=False, default=True)

    def __repr__(self) -> str:
        return f"{self.first_name} {self.last_name}"
    

class Stats(db.Model):
    __tablename__ = "stats"
    
    id = sa.Column(sa.Integer, primary_key=True)
    happy_clients = sa.Column(sa.Integer, nullable=False, default=0)
    projects = sa.Column(sa.Integer, nullable=False, default=0)
    hours_of_support = sa.Column(sa.Integer, nullable=False, default=0)
    hard_works = sa.Column(sa.Integer, nullable=False, default=0)   
    is_active = sa.Column(sa.Boolean, nullable=False, default=True)

    def __repr__(self) -> str:
        return "Stats"
    

class Skils(db.Model):
    __tablename__ = "skils"

    id = sa.Column(sa.Integer, primary_key=True)
    name = sa.Column(sa.String(30), nullable=False)
    procent = sa.Column(sa.Integer, nullable=False, default=0) 
    is_active = sa.Column(sa.Boolean, nullable=False, default=True)
    
    def __repr__(self) -> str:
        return self.name
    

class Resume(db.Model):
    __tablename__ = "resume"

    id = sa.Column(sa.Integer, primary_key=True)
    full_name = sa.Column(sa.String(120), nullable=False)
    summary = sa.Column(sa.Text, nullable=False)
    education = sa.Column(sa.Text, nullable=False)
    professional_experience = sa.Column(sa.Text, nullable=False)
    is_active = sa.Column(sa.Boolean, nullable=False, default=True)

    def __repr__(self) -> str:
        return self.full_name
    

app/models/user.py
from flask_login import UserMixin
from flask_sqlalchemy.model import sa
from app import db


class User(db.Model, UserMixin):
    __tablename__ = "users"
    
    id = sa.Column(sa.Integer, primary_key=True)
    first_name = sa.Column(sa.String(120), nullable=True)
    last_name = sa.Column(sa.String(120), nullable=True)
    username = sa.Column(sa.String(150), unique=True, nullable=False, index=True)
    email = sa.Column(sa.String(150), nullable=True)
    password = sa.Column(sa.String(150), nullable=False)
    is_active = sa.Column(sa.Boolean, default=True)

    def __repr__(self):
        return f"<User {self.username}>"

app/forms/__init__.py
from .auth import * # noqa

app/__init__.py
from pathlib import Path

from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_bcrypt import Bcrypt
from flask_debugtoolbar import DebugToolbarExtension
from flask_caching import Cache
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView
from flask_babel import Babel

from .core.settings import config


base_dir = Path(__file__).resolve().parent

db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()
bcrypt = Bcrypt()
# toolbar = DebugToolbarExtension()
cache = Cache()
admin = Admin()
admin.name = "Flask Admin"
admin.template_mode = "bootstrap4" # Bootstrap(2, 3, 4)
admin.index_view._template = "admin/index.html"
admin.base_template = "admin/base.html"

babel = Babel()


def create_app(config_class: str = "app.core.settings.config"):
    app = Flask(__name__)
    app.config.from_object(config_class)
    
    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)
    bcrypt.init_app(app)
    cache.init_app(app)
    babel.init_app(app)

    login_manager.login_view = "routes.auth.login"

    if config.DEBUG:
        admin.init_app(app)

        from app.models import (
            User, About, Stats, Skils, Resume
        )
        admin.add_view(ModelView(User, db.session))
        admin.add_view(ModelView(About, db.session))
        admin.add_view(ModelView(Stats, db.session))
        admin.add_view(ModelView(Skils, db.session))
        admin.add_view(ModelView(Resume, db.session))
    
    from app import routes
    
    app.register_blueprint(routes.site_dp)
    app.register_blueprint(routes.auth_dp)
    
    return app

app/routes/__init__.py
from .site import dp as site_dp # noqa
from .auth import dp as auth_dp # noqa

app/routes/auth.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from flask_login import login_user, logout_user, login_required, current_user

from app.forms import LoginForm, RegistrationForm
from app.models import User
from app import bcrypt, login_manager, db


dp = Blueprint("auth", __name__)


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


dp.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("site.home"))
    
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()

        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=True)
            next_page = request.args.get("next")

            return redirect(next_page) if next_page else redirect(url_for("site.home"))
        
        flash(f"Login unsuccessfully. Pleace check username or password", "danger")
    
    return render_template("auth/login.html", form=form)


@dp.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("site.home"))
    
    form = RegistrationForm()
    
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode("utf-8")

        user = User(
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            username=form.username.data,
            email=form.email.data,
            password=hashed_password
        )
        db.session.add(user)
        db.session.commit()
        db.session.refresh(user)

        flash("User successfully registered", "success")
        return redirect(url_for("auth.login"))
    
    return render_template("auth/register.html", form=form)


@dp.route("/logout", methods=["GET", "POST"])
@login_required
def logout():
    logout_user()
    flash(f"{current_user.username} user successfully loged out", "success")
    return redirect(url_for("home"))

app/routes/site.py
from flask import render_template, Blueprint


dp = Blueprint("site", __name__)


@dp.route("/")
@dp.route("/portfolio")
def portfolio():
    return render_template("index.html")


@dp.route('/portfolio-detail')
def portfolio_detail():
    return render_template("/portfolio-details.html")


@dp.route("/service-detail")
def service_detail():
    return render_template("/service-details.html")


@dp.route("/starter-page")
def starter_page():
    return render_template("/starter-page.html")

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>{% block title %} Base {% endblock %}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{{ url_for('static', filename='assets/img/favicon.png') }}" rel="icon">
  <link href="{{ url_for('static', filename='assets/img/apple-touch-icon.png') }}" rel="apple-touch-icon">

  <!-- Fonts -->
  <link href="https://fonts.googleapis.com" rel="preconnect">
  <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{{ url_for('static', filename='assets/vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
  <link href="{{ url_for('static', filename='assets/vendor/bootstrap-icons/bootstrap-icons.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='assets/vendor/aos/aos.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='assets/vendor/glightbox/css/glightbox.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='assets/vendor/swiper/swiper-bundle.min.css') }}" rel="stylesheet">

  <!-- Main CSS File -->
  <link href="{{ url_for('static', filename='assets/css/main.css') }}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: iPortfolio
  * Template URL: https://bootstrapmade.com/iportfolio-bootstrap-portfolio-websites-template/
  * Updated: Jun 29 2024 with Bootstrap v5.3.3
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body class="index-page">
    {% block content %}
    {% endblock %}
<footer id="footer" class="footer position-relative light-background">

    <div class="container">
        <div class="copyright text-center ">
        <p>© <span>Copyright</span> <strong class="px-1 sitename">iPortfolio</strong> <span>All Rights Reserved</span></p>
        </div>
        <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you've purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: [buy-url] -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
    </div>

    </footer>

    <!-- Scroll Top -->
    <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Preloader -->
    <div id="preloader"></div>

    <!-- Vendor JS Files -->
    <script src="{{ url_for('static', filename='assets/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
    <script src="{{ url_for('static', filename='assets/vendor/php-email-form/validate.js') }}"></script>
    <script src="{{ url_for('static', filename='assets/vendor/aos/aos.js') }}"></script>
    <script src="{{ url_for('static', filename='assets/vendor/typed.js/typed.umd.js') }}"></script>
    <script src="{{ url_for('static', filename='assets/vendor/purecounter/purecounter_vanilla.js') }}"></script>
    <script src="{{ url_for('static', filename='assets/vendor/waypoints/noframework.waypoints.js') }}"></script>
    <script src="{{ url_for('static', filename='assets/vendor/glightbox/js/glightbox.min.js') }}"></script>
    <script src="{{ url_for('static', filename='assets/vendor/imagesloaded/imagesloaded.pkgd.min.js') }}"></script>
    <script src="{{ url_for('static', filename='assets/vendor/isotope-layout/isotope.pkgd.min.js') }}"></script>
    <script src="{{ url_for('static', filename='assets/vendor/swiper/swiper-bundle.min.js') }}"></script>

    <!-- Main JS File -->
    <script src="{{ url_for('static', filename='assets/js/main.js') }}"></script>

</body>

</html>

app/templates/portfolio-details.html
{% extends 'base.html' %}
{% block title %} Portfolio Details {% endblock %}
{% block content %}
  <main class="main">

    <!-- Page Title -->
    <div class="page-title dark-background">
      <div class="container d-lg-flex justify-content-between align-items-center">
        <h1 class="mb-2 mb-lg-0">Portfolio Details</h1>
        <nav class="breadcrumbs">
          <ol>
            <li><a href="{{ url_for('site.portfolio') }}">Home</a></li>
            <li class="current">Portfolio Details</li>
          </ol>
        </nav>
      </div>
    </div><!-- End Page Title -->

    <!-- Portfolio Details Section -->
    <section id="portfolio-details" class="portfolio-details section">

      <div class="container" data-aos="fade-up" data-aos-delay="100">

        <div class="row gy-4">

          <div class="col-lg-8">
            <div class="portfolio-details-slider swiper init-swiper">

              <script type="application/json" class="swiper-config">
                {
                  "loop": true,
                  "speed": 600,
                  "autoplay": {
                    "delay": 5000
                  },
                  "slidesPerView": "auto",
                  "pagination": {
                    "el": ".swiper-pagination",
                    "type": "bullets",
                    "clickable": true
                  }
                }
              </script>

              <div class="swiper-wrapper align-items-center">

                <div class="swiper-slide">
                  <img src="{{ url_for('static', filename='assets/img/portfolio/app-1.jpg') }}" alt="">
                </div>

                <div class="swiper-slide">
                  <img src="{{ url_for('static', filename='assets/img/portfolio/product-1.jpg') }}" alt="">
                </div>

                <div class="swiper-slide">
                  <img src="{{ url_for('static', filename='assets/img/portfolio/branding-1.jpg') }}" alt="">
                </div>

                <div class="swiper-slide">
                  <img src="{{ url_for('static', filename='assets/img/portfolio/books-1.jpg') }}" alt="">
                </div>

              </div>
              <div class="swiper-pagination"></div>
            </div>
          </div>

          <div class="col-lg-4">
            <div class="portfolio-info" data-aos="fade-up" data-aos-delay="200">
              <h3>Project information</h3>
              <ul>
                <li><strong>Category</strong>: Web design</li>
                <li><strong>Client</strong>: ASU Company</li>
                <li><strong>Project date</strong>: 01 March, 2020</li>
                <li><strong>Project URL</strong>: <a href="#">www.example.com</a></li>
              </ul>
            </div>
            <div class="portfolio-description" data-aos="fade-up" data-aos-delay="300">
              <h2>Exercitationem repudiandae officiis neque suscipit</h2>
              <p>
                Autem ipsum nam porro corporis rerum. Quis eos dolorem eos itaque inventore commodi labore quia quia. Exercitationem repudiandae officiis neque suscipit non officia eaque itaque enim. Voluptatem officia accusantium nesciunt est omnis tempora consectetur dignissimos. Sequi nulla at esse enim cum deserunt eius.
              </p>
            </div>
          </div>

        </div>

      </div>

    </section><!-- /Portfolio Details Section -->

  </main>
{% endblock %}

app/templates/service-details.html
{% extends 'base.html' %}
{% block title %} Service details {% endblock %}
{% block content %}
  <main class="main">

    <!-- Page Title -->
    <div class="page-title dark-background">
      <div class="container d-lg-flex justify-content-between align-items-center">
        <h1 class="mb-2 mb-lg-0">Service Details</h1>
        <nav class="breadcrumbs">
          <ol>
            <li><a href="{{ url_for('site.portfolio') }}">Home</a></li>
            <li class="current">Service Details</li>
          </ol>
        </nav>
      </div>
    </div><!-- End Page Title -->

    <!-- Service Details Section -->
    <section id="service-details" class="service-details section">

      <div class="container">

        <div class="row gy-4">

          <div class="col-lg-4" data-aos="fade-up" data-aos-delay="100">
            <div class="services-list">
              <a href="#" class="active">Web Design</a>
              <a href="#">Software Development</a>
              <a href="#">Product Management</a>
              <a href="#">Graphic Design</a>
              <a href="#">Marketing</a>
            </div>

            <h4>Enim qui eos rerum in delectus</h4>
            <p>Nam voluptatem quasi numquam quas fugiat ex temporibus quo est. Quia aut quam quod facere ut non occaecati ut aut. Nesciunt mollitia illum tempore corrupti sed eum reiciendis. Maxime modi rerum.</p>
          </div>

          <div class="col-lg-8" data-aos="fade-up" data-aos-delay="200">
            <img src="{{ url_for('static', filename='assets/img/services.jpg') }}" alt="" class="img-fluid services-img">
            <h3>Temporibus et in vero dicta aut eius lidero plastis trand lined voluptas dolorem ut voluptas</h3>
            <p>
              Blanditiis voluptate odit ex error ea sed officiis deserunt. Cupiditate non consequatur et doloremque consequuntur. Accusantium labore reprehenderit error temporibus saepe perferendis fuga doloribus vero. Qui omnis quo sit. Dolorem architecto eum et quos deleniti officia qui.
            </p>
            <ul>
              <li><i class="bi bi-check-circle"></i> <span>Aut eum totam accusantium voluptatem.</span></li>
              <li><i class="bi bi-check-circle"></i> <span>Assumenda et porro nisi nihil nesciunt voluptatibus.</span></li>
              <li><i class="bi bi-check-circle"></i> <span>Ullamco laboris nisi ut aliquip ex ea</span></li>
            </ul>
            <p>
              Est reprehenderit voluptatem necessitatibus asperiores neque sed ea illo. Deleniti quam sequi optio iste veniam repellat odit. Aut pariatur itaque nesciunt fuga.
            </p>
            <p>
              Sunt rem odit accusantium omnis perspiciatis officia. Laboriosam aut consequuntur recusandae mollitia doloremque est architecto cupiditate ullam. Quia est ut occaecati fuga. Distinctio ex repellendus eveniet velit sint quia sapiente cumque. Et ipsa perferendis ut nihil. Laboriosam vel voluptates tenetur nostrum. Eaque iusto cupiditate et totam et quia dolorum in. Sunt molestiae ipsum at consequatur vero. Architecto ut pariatur autem ad non cumque nesciunt qui maxime. Sunt eum quia impedit dolore alias explicabo ea.
            </p>
          </div>

        </div>

      </div>

    </section><!-- /Service Details Section -->

  </main>
{% endblock %}

app/templates/starter-page.html
{% extends 'base.html' %}
{% block title %} Starter page {% endblock %}
{% block content %}
  <main class="main">

    <!-- Page Title -->
    <div class="page-title dark-background">
      <div class="container d-lg-flex justify-content-between align-items-center">
        <h1 class="mb-2 mb-lg-0">Starter Page</h1>
        <nav class="breadcrumbs">
          <ol>
            <li><a href="index.html">Home</a></li>
            <li class="current">Starter Page</li>
          </ol>
        </nav>
      </div>
    </div><!-- End Page Title -->

    <!-- Starter Section Section -->
    <section id="starter-section" class="starter-section section">

      <!-- Section Title -->
      <div class="container section-title" data-aos="fade-up">
        <h2>Starter Section</h2>
        <p>Necessitatibus eius consequatur ex aliquid fuga eum quidem sint consectetur velit</p>
      </div><!-- End Section Title -->

      <div class="container" data-aos="fade-up">
        <p>Use this page as a starter for your own custom pages.</p>
      </div>

    </section><!-- /Starter Section Section -->

  </main>
{% endblock %}